coverage:
  status:
    project:
      default:
        threshold: 1%
    patch:
      default:
        target: 80%

ignore:
  - "**/*.test.ts"
  - "**/*.test.tsx"
  - "**/*.stories.ts"
  - "**/*.stories.tsx"
  - "e2e/**"
  - ".storybook/**"
